name: Questor

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    if: contains(github.event.head_commit.message, 'deploy-production')

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.4.0]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: ${{ matrix.node-version }}
      #     cache: 'npm'

      - name: Install Dependencies and Build Backend
        run: |
          pm2 resurrect
          pm2 stop all
          pwd
          cd backend
          npm ci

      - name: Install Dependencies and Build Frontend
        run: |
          pwd
          cd kahoot
          rm -rf .next
          npm i --force
          npm run build

      - name: Restart PM2 services
        run: |
          pm2 start all
