name: Questor

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    if: contains(github.event.head_commit.message, 'deploy-production')

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.4.0]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Resurrect PM2 Processes if Needed
        run: |
          pm2 resurrect || echo "No previous PM2 state to restore."

      - name: Install Dependencies and Build Backend
        run: |
          pm2 stop all || echo "No PM2 apps running."
          cd backend
          npm ci

      - name: Install Dependencies and Build Frontend
        run: |
          cd kahoot
          npm i --force
          npm run build

      - name: Restart PM2 Services and Save
        run: |
          pm2 start all
          pm2 save
