name: Questor

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  pull_code:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pull Latest Code
        run: |
          git reset --hard
          git pull origin master

  build:
    needs: pull_code
    if: contains(github.event.head_commit.message, 'deploy-production')
    runs-on: self-hosted

    steps:
      - name: Stop PM2 Services
        run: |
          pm2 stop all || echo "No PM2 services running"

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm ci

      - name: Install Frontend Dependencies and Build
        run: |
          cd kahoot
          npm i --force
          npm run build

      - name: Restart PM2 Services
        run: |
          pm2 start all
